#!/usr/bin/env bash
##
# COLORS
# ~/.bash-tui/.cached-colors
# BTUI_s[red]=34
# BTUI_n[34]=red
export BTUI_ctop=256
export NC="\e[0;0m" ## NC doesn't exist on the 256 table
export BTUI_cache=~/.bash-tui/.cached-colors
export BTUI_configs=(/etc/bash-tui-colors.conf ~/.bash-tui-colors.conf) # Lowest to highest priority

export BTUI_cp="\e[38;5;%dm" ## Color Pattern
export BTUI_ph="Cantami o diva del pelide Achille l'ira funesta..." ## Phrase used in colorget/colorshow

[ ! -d ~/.bash-tui ] && mkdir ~/.bash-tui

colorcache() {
  local x=
for i in 1;do
  [ ! -z $1 ] && [ "$1" = '-s' ] && break ## loaded cache instead
  local uf=
  declare -a TMPC=
  for f in ${BTUI_configs[@]};do
    [ ! -e "$f" ] && continue
    uf=1
    for cl in $(cat "${f}" | grep -e '^[[:space:]]*colorset' | sed -E "s/^[[:space:]]*colorset[[:space:]]{1,}([0-9]{1,})[[:space:]]{1,}([a-zA-Z]+[a-zA-Z0-9]*)$/TMPC[\1]=\2/g"); do
      # we create the TMPC
      ## TODO: I don't like evals...
      eval "${cl}"
    done 
  done
  [ -z $uf ] && echo "ERROR: There was a problem importing your colors..." && return 1
done
  [ -z "${TMPC[*]}" ] && [ -z "${BTUI_n[*]}" ] && echo "ERROR: I could not find any colors from your defaults, check the documentation." && return 1
  ## TODO: the cache file can be multisession, but I don't feel like it right now
  ## you can just slam them in there .bash-tui/.sessions/hdf6t32rg23.colors
  ## but first you need to create bash-tui sessions
  #CACHE_now=$(date +%s)
  echo "#!/usr/bin/env bash" > $BTUI_cache
  echo "## BASH-TUI: File autogenerated, don't modify this, use colorset/colorimport/colorcache instead" >> $BTUI_cache
  #echo "BTUI_c="
  echo "declare -A BTUI_s" >> $BTUI_cache
  echo "declare -a BTUI_n" >> $BTUI_cache
  echo "BTUI_s=" >> $BTUI_cache
  echo "BTUI_n=" >> $BTUI_cache
  # Easy Mapping
  for c in $(seq 0 ${BTUI_ctop}); do
    ## Your current save
    if [ ! -z ${BTUI_save[$c]+_} ] && (( ${#BTUI_save[$c]} )); then
      #echo "1"
      echo "BTUI_s[${BTUI_save[$c]}]=$c" >> $BTUI_cache
      echo "BTUI_n[$c]='${BTUI_save[$c]}'" >> $BTUI_cache 
      eval "export ${BTUI_save[$c]}=\"$(printf $BTUI_cp $c)\""
    
    ## From cache
    elif [ ! -z ${BTUI_n[$c]+_} ]; then
      #echo "2"
      echo "BTUI_s[${BTUI_n[$c]}]=$c" >> $BTUI_cache
      echo "BTUI_n[$c]='${BTUI_n[$c]}'" >> $BTUI_cache 
      eval "export ${BTUI_n[$c]}=\"$(printf $BTUI_cp $c)\""

    ## From file (only without -s)
    elif [ ! -z ${TMPC[$c]+_} ]; then
      #echo "3"
      echo "BTUI_s[${TMPC[$c]}]=$c" >> $BTUI_cache
      echo "BTUI_n[$c]='${TMPC[$c]}'" >> $BTUI_cache 
      eval "export ${TMPC[$c]}=\"$(printf $BTUI_cp $c)\""

    #else
      #echo "BTUI_s[C$c]=${c}" >> $BTUI_cache && continue
    fi
  done
  echo "## Colors cached on $(date)" >> $BTUI_cache
  unset TMPC # good boys clean up after themselves
return 0
}


## Import colors
# this is rather cheap if you simply load and reload the same tiny file over and over
colorimport() {
  [ ! -e $BTUI_cache ] && colorcache
  [ ! -e $BTUI_cache ] && echo "ERROR: There was a problem with your color cache file $BTUI_cache." && return 1 
  return 0
}
## Get Colors
# imports colors, prints the color you asked via number
# ANY second parameter will skip the import
colorget() { 
  ( [ -z $1 ] || ! [[ $1 =~ [0-9]+ ]] ) && echo "ERROR: I need a color id as first parameter between 0 and ${BTUI_ctop}" && return 1
  [ -z $2 ] && colorimport && . $BTUI_cache
  _c=$(printf $BTUI_cp $1)
  cc=$1
  [ ! -z ${BTUI_n[$1]+_} ] && cc=${BTUI_n[$1]}
  echo -e "${_c}$BTUI_ph : $cc ${NC} "

  return 0
}
## Set a new color
# you want to set a new color? there ya go..
colorset() {
  colorimport && . $BTUI_cache || return 1
  local index=$1
  local label=$2
  ( [ -z $index ] || ! [[ $index =~ [0-9]+ ]] ) && echo "ERROR: I need a color id as first parameter between 0 and ${BTUI_ctop}" && return 1
  ( [ -z $label ] || ! [[ $label =~ [a-zA-Z]+[a-zA-Z0-9]* ]] ) && echo "ERROR: I need a color name as second parameter starting with a letter" && return 1

  # The color will be set unless it exists already with the same name... for obviousliestest reasons
  ( [ ! -z "${BTUI_n[$index]+_}" ] || [ "${BTUI_n[$index]}" = "$label"  ] ) && return 2

  # Override in cache
  declare -a BTUI_save= && BTUI_save[$index]=$label && colorcache -s && return 0
return 1
}
# Show rainbow
colorshow() {
  colorimport && . $BTUI_cache || return 1
  for c in $(seq 0 ${BTUI_ctop}); do
    colorget $c skip-import
  done
return 0
}
# Export your customs
colorexport() {
  colorimport && . $BTUI_cache || return 1
  for c in $(seq 0 ${BTUI_ctop}); do
    [ "${Bclrs[$c]}" != "C${c}" ] && echo "$c ${Bclrs[$c]}"
  done
}
# Cause I said so
colorreset() {
  colorcache
}

##### DO IT
# cache colors
colorcache 
