# Build RPM
name: Build RPM Package

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set Variables
      id: variables # This ID is used to reference outputs from this step
      run: |
        echo "RPM_VERSION=$(echo ${GITHUB_REF#refs/heads/release/})" >> $GITHUB_ENV
        echo "RPM_RELEASE=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

    - name: Prepare Source
      run: |
        TAR_NAME="bash-tui-${{ env.RPM_VERSION }}-${{ env.RPM_RELEASE }}.tar.gz"
        mkdir -p $HOME/rpmbuild/SOURCES
        tar czf $HOME/rpmbuild/SOURCES/$TAR_NAME --exclude=.git .

    - name: Build RPM
      run: |
        rpmbuild -ba bash-tui.spec \
          --define "_sourcedir $HOME/rpmbuild/SOURCES" \
          --define "tar_version $TAR_VERSION" \
          --define "rpm_version $RPM_VERSION" \
          --define "rpm_release $RPM_RELEASE" \
          --define "_srcrpmdir $HOME" \
          --define "_rpmdir $HOME" 

    - name: Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: bash-tui
        path: |
          $HOME/rpmbuild/RPMS/**/*.rpm

