# Build RPM
name: Build RPM Package

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RPM_VERSION: ${{ steps.set_vars.outputs.rpm_version }}
      RPM_RELEASE: ${{ steps.set_vars.outputs.rpm_release }}
      TAR_VERSION: ${{ steps.set_vars.outputs.tar_version }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set Variables
      id: set_vars
      run: |
        echo "::set-output name=rpm_version::$(echo "${{ github.ref }}" | sed 's|refs/heads/release/||')"
        echo "::set-output name=rpm_release::$(git rev-parse --short=8 HEAD)"
        echo "::set-output name=tar_version::${{ steps.set_vars.outputs.rpm_version }}-${{ steps.set_vars.outputs.rpm_release }}"

    - name: Prepare Source
      run: |
        TAR_NAME="bash-tui-${{ env.TAR_VERSION }}.tar.gz"
        mkdir -p $HOME/rpmbuild/SOURCES
        tar czf $HOME/rpmbuild/SOURCES/$TAR_NAME --exclude=.git .

    - name: Build RPM
      run: |
        rpmbuild -ba bash-tui.spec \
          --define "_sourcedir $HOME/rpmbuild/SOURCES" \
          --define "tar_version $TAR_VERSION" \
          --define "rpm_version $RPM_VERSION" \
          --define "rpm_release $RPM_RELEASE" \
          --define "_srcrpmdir $HOME" \
          --define "_rpmdir $HOME" 

    - name: Upload RPM
      uses: actions/upload-artifact@v2
      with:
        name: bash-tui
        path: |
          ${HOME}/*.rpm

